name: Deploy to InfinityFree
on:
  push:
    branches:
      - deploy # Robot chỉ kích hoạt khi bạn đẩy code vào nhánh deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Chỉ đẩy thư mục wp-content để tránh lỗi hệ thống và nhanh hơn
          local-dir: ./wp-content/
          server-dir: /htdocs/wp-content/
          delete: false
